### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by HITESH2002-JAIN** [AILab-CVC/YOLO-World#139]
I am facing this issue while running `pip install -e .`
```
pip install -e .
Obtaining file:///home/ubuntu/YOLO-World
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting mmyolo@ git+https://github.com/onuralpszr/mmyolo.git
  Cloning https://github.com/onuralpszr/mmyolo.git to /tmp/pip-install-hncp326u/mmyolo_7458f39ca31f46ad927b651f4674bf59
  Running command git clone --filter=blob:none --quiet https://github.com/onuralpszr/mmyolo.git /tmp/pip-install-hncp326u/mmyolo_7458f39ca31f46ad927b651f4674bf59
  Resolved https://github.com/onuralpszr/mmyolo.git to commit 4d97b3a06609dba94b8ec584be2f2029cfdb7519
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hncp326u/mmyolo_7458f39ca31f46ad927b651f4674bf59/setup.py", line 11, in <module>
          from torch.utils.cpp_extension import BuildExtension
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/__init__.py", line 4, in <module>
          from .throughput_benchmark import ThroughputBenchmark
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/throughput_benchmark.py", line 2, in <module>
          import torch._C
      ModuleNotFoundError: No module named 'torch._C'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
NVCC version:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by B10515007** [comment]
This instruction may help a lot https://github.com/AILab-CVC/YOLO-World/issues/573
