### ISSUE TITLE
关于昨晚上最新提交的easydeploy中的export_onnx

### ISSUE THREAD

**Issue by xiyangyang99** [AILab-CVC/YOLO-World#151]

**Comment by taofuyu** [comment]
AttributeError: 'YOLOWorldDetector' object has no attribute 'texts'
报错很明显嘛可以打个断点单步调试看看为什么。应该是export_onnx.py需要你自己加一句model.reparameterize(), 这个[函数](https://github.com/AILab-CVC/YOLO-World/blob/7071abbcba11075ccafcdd2ae0805c5c164d15be/yolo_world/models/detectors/yolo_world.py#L58)里把self.texts的值给赋上

**Comment by xiyangyang99** [comment]
就在刚刚你发给我的时候，我恰好断点debug完！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] 关于昨晚上最新提交的easydeploy中的export_onnx (Issue #151)





 
AttributeError: 'YOLOWorldDetector' object has no attribute 'texts'
 报错很明显嘛可以打个断点单步调试看看为什么。应该是export_onnx.py需要你自己加一句model.reparameterize(), 这个函数里把self.texts的值给赋上

**Comment by xiyangyang99** [comment]
兄台，我给text赋值之后还是遇到了torch.onnx.errors.SymbolicValueError:&nbsp;Unsupported:&nbsp;ONNX&nbsp;export&nbsp;of&nbsp;operator&nbsp;adaptive_max_pool2d,&nbsp;output&nbsp;size&nbsp;that&nbsp;are&nbsp;not&nbsp;factor&nbsp;of&nbsp;input&nbsp;size.&nbsp;Please&nbsp;feel&nbsp;free&nbsp;to&nbsp;request&nbsp;support&nbsp;or&nbsp;submit&nbsp;a&nbsp;pull&nbsp;request&nbsp;on&nbsp;PyTorch&nbsp;GitHub:&nbsp;https://github.com/pytorch/pytorch/issues&nbsp;&nbsp;[Caused&nbsp;by&nbsp;the&nbsp;value&nbsp;'1303&nbsp;defined&nbsp;in&nbsp;(%1303&nbsp;:&nbsp;Long(2,&nbsp;strides=[1],&nbsp;device=cpu)&nbsp;=&nbsp;onnx::Constant[value=&nbsp;3&nbsp;&nbsp;3&nbsp;[&nbsp;CPULongType{2}&nbsp;]]()
)'&nbsp;(type&nbsp;'Tensor')&nbsp;in&nbsp;the&nbsp;TorchScript&nbsp;graph.&nbsp;The&nbsp;containing&nbsp;node&nbsp;has&nbsp;kind&nbsp;'onnx::Constant'.]&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;Inputs:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Empty
&nbsp;&nbsp;&nbsp;&nbsp;Outputs:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#0:&nbsp;1303&nbsp;defined&nbsp;in&nbsp;(%1303&nbsp;:&nbsp;Long(2,&nbsp;strides=[1],&nbsp;device=cpu)&nbsp;=&nbsp;onnx::Constant[value=&nbsp;3&nbsp;&nbsp;3&nbsp;[&nbsp;CPULongType{2}&nbsp;]]()
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;&nbsp;(type&nbsp;'Tensor')‍

这个问题？你遇到了嘛？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] 关于昨晚上最新提交的easydeploy中的export_onnx (Issue #151)





 
AttributeError: 'YOLOWorldDetector' object has no attribute 'texts'
 报错很明显嘛可以打个断点单步调试看看为什么。应该是export_onnx.py需要你自己加一句model.reparameterize(), 这个函数里把self.texts的值给赋上

**Comment by wondervictor** [comment]
@xiyangyang99 使用最新的code吧，目前我更新了`deploy/export_onnx.py`。

**Comment by xiyangyang99** [comment]
> @xiyangyang99 使用最新的code吧，目前我更新了`deploy/export_onnx.py`。

这是使用最新的export_onnx.py导出的时候输出如下：
Traceback (most recent call last):
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/yolo-world-v2/YOLO-World-master/deploy/export_onnx.py", line 168, in <module>
    main()
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/yolo-world-v2/YOLO-World-master/deploy/export_onnx.py", line 127, in main
    deploy_model(fake_input)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/yolo-world-v2/YOLO-World-master/deploy/easydeploy/model/model.py", line 168, in forward
    return self.pred_by_feat(*neck_outputs)
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/yolo-world-v2/YOLO-World-master/deploy/easydeploy/model/model.py", line 145, in pred_by_feat
    bboxes = bbox_decoder(flatten_priors[None], flatten_bbox_preds,
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmyolo/models/task_modules/coders/distance_point_bbox_coder.py", line 45, in decode
    assert points.size(-2) == pred_bboxes.size(-2)
AssertionError
备注：
config和weights  都是之前版本的fintue_coco里面的训练的。export是最新的版本。

**Comment by wondervictor** [comment]
麻烦提供一下调用的脚本吧

**Comment by xiyangyang99** [comment]
红色框里面的config。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] 关于昨晚上最新提交的easydeploy中的export_onnx (Issue #151)





 
麻烦提供一下调用的脚本吧

**Comment by xiyangyang99** [comment]
用绿色的config训练之后的模型可转onnx，红色的暂时不行。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] 关于昨晚上最新提交的easydeploy中的export_onnx (Issue #151)





 
麻烦提供一下调用的脚本吧

**Comment by wondervictor** [comment]
@xiyangyang99 目前看不到您提供的信息。

**Comment by xiyangyang99** [comment]
> @xiyangyang99 目前看不到您提供的信息。

![{AZXMGTR%ZSAI8RBA 0O6OV](https://github.com/AILab-CVC/YOLO-World/assets/32487883/0d4b235a-2795-4151-b269-cdddac6f92c3)
红色不能转onnx，绿色可以。现在转tensorrt还有点问题。onnx精度能对其。

**Comment by wondervictor** [comment]
我们目前支持v2的模型和efficientneck的模型转换，后期将不会再支持v1的模型了

**Comment by xiyangyang99** [comment]
后面会分割支持coco数据集格式的吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 晚上6:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] 关于昨晚上最新提交的easydeploy中的export_onnx (Issue #151)





 
我们目前支持v2的模型和efficientneck的模型转换，后期将不会再支持v1的模型了

**Comment by wondervictor** [comment]
目前分割已经支持COCO的格式了，但是ONNX目前还不支持分割

**Comment by xiyangyang99** [comment]
有些小bug，在debug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] 关于昨晚上最新提交的easydeploy中的export_onnx (Issue #151)





 
目前分割已经支持COCO的格式了，但是ONNX目前还不支持分割

**Comment by xiyangyang99** [comment]
> 目前分割已经支持COCO的格式了，但是ONNX目前还不支持分割

Traceback (most recent call last):
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/yolo-world-v2/YOLO-World/tools/train.py", line 120, in <module>
    main()
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/yolo-world-v2/YOLO-World/tools/train.py", line 116, in main
    runner.train()
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1728, in train
    self._train_loop = self.build_train_loop(
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1520, in build_train_loop
    loop = LOOPS.build(
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/yolo-world-v2/YOLO-World/yolo_world/datasets/mm_dataset.py", line 25, in __init__
    self.dataset = DATASETS.build(dataset)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmyolo/datasets/yolov5_coco.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/mmdetection-3.0.0/mmdet/datasets/base_det_dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/home/bowen/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmyolo/datasets/yolov5_coco.py", line 27, in full_init
    self.data_list = self.load_data_list()
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/mmdetection-3.0.0/mmdet/datasets/lvis.py", line 619, in load_data_list
    raw_img_info['file_name'] = raw_img_info['coco_url'].replace(
KeyError: 'coco_url'

Process finished with exit code 1

这是用segment里面的config作为配置文件，python train.pyd 的报错。不知道你们那边有这个没有。
