### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/lvis/lvis_v1_minival_inserted_image_name.json'

### ISSUE THREAD

**Issue by Hongyuan-Liu** [AILab-CVC/YOLO-World#178]
执行
python deploy/export_onnx.py \
       ./configs/pretrain/yolo_world_v2_l_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py \
       ./weights/yolo_world_v2_l_obj365v1_goldg_cc3mlite_pretrain-ca93cd1f.pth \
       --custom-text data/texts/lvis_v1_class_texts.json \
       --opset 11
报错误：
Traceback (most recent call last):
  File "/dataset/liuhongyuan/workspace/YOLO-World/deploy/export_onnx.py", line 170, in <module>
    main()
  File "/dataset/liuhongyuan/workspace/YOLO-World/deploy/export_onnx.py", line 118, in main
    baseModel = build_model_from_cfg(args.config, args.checkpoint, args.device)
  File "/dataset/liuhongyuan/workspace/YOLO-World/deploy/export_onnx.py", line 80, in build_model_from_cfg
    model = init_detector(config_path, checkpoint_path, device=device)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmdet/apis/inference.py", line 102, in init_detector
    metainfo = DATASETS.build(test_dataset_cfg).metainfo
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/dataset/liuhongyuan/workspace/YOLO-World/yolo_world/datasets/mm_dataset.py", line 25, in __init__
    self.dataset = DATASETS.build(dataset)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmyolo/datasets/yolov5_coco.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmdet/datasets/base_det_dataset.py", line 51, in __init__
    super().__init__(*args, **kwargs)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmyolo/datasets/yolov5_coco.py", line 27, in full_init
    self.data_list = self.load_data_list()
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/mmdet/datasets/lvis.py", line 606, in load_data_list
    self.lvis = LVIS(local_path)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/lvis/lvis.py", line 27, in __init__
    self.dataset = self._load_json(annotation_path)
  File "/home/liuhongyuan/workspace/miniconda3/envs/yolo-world/lib/python3.10/site-packages/lvis/lvis.py", line 35, in _load_json
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/lvis/lvis_v1_minival_inserted_image_name.json'

**Comment by wufei-png** [comment]
https://huggingface.co/GLIPModel/GLIP/blob/main/lvis_v1_minival_inserted_image_name.json 这里有，google搜一下文件名

**Comment by Hongyuan-Liu** [comment]
> https://huggingface.co/GLIPModel/GLIP/blob/main/lvis_v1_minival_inserted_image_name.json 这里有,google搜一下文件名
你好，我下载了json文件，可以导出成功，但是我onnx推理后，没有结果产生，我用huggingface.co在线导出的yolowl.onnx，可以正常输出结果？但是为什么输出的结果是好多类别，导出的onnx模型，不能像groundingdino那样传入文本，输出对于的检测结果吗？

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
