### ISSUE TITLE
分布式训练bug

### ISSUE THREAD

**Issue by xiyangyang99** [AILab-CVC/YOLO-World#192]
配置好本地config之后，用8卡混合精度训练，报错如下，反向传播过程中出现问题，
Traceback (most recent call last):
  File "/home/quchunguang/003-large-model/bowen/YOLO-World-master/./tools/train.py", line 120, in <module>
    main()
  File "/home/quchunguang/003-large-model/bowen/YOLO-World-master/./tools/train.py", line 116, in main
    runner.train()
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/runner.py", l                        ine 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/loops.py", li                        ne 96, in run
    self.run_epoch()
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/loops.py", li                        ne 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/loops.py", li                        ne 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/model/wrappers/distr                        ibuted.py", line 123, in train_step
    optim_wrapper.update_params(parsed_loss)
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/optim/optimizer/opti                        mizer_wrapper.py", line 196, in update_params
    self.backward(loss)
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/optim/optimizer/amp_                        optimizer_wrapper.py", line 126, in backward
    self.loss_scaler.scale(loss).backward(**kwargs)
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/torch/_tensor.py", line 363,                         in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/torch/autograd/__init__.py",                         line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by xiyangyang99** [comment]
> 配置好本地config之后，用8卡混合精度训练，报错如下，反向传播过程中出现问题， Traceback (most recent call last): File "/home/quchunguang/003-large-model/bowen/YOLO-World-master/./tools/train.py", line 120, in main() File "/home/quchunguang/003-large-model/bowen/YOLO-World-master/./tools/train.py", line 116, in main runner.train() File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/runner.py", l ine 1777, in train model = self.train_loop.run() # type: ignore File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/loops.py", li ne 96, in run self.run_epoch() File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/loops.py", li ne 112, in run_epoch self.run_iter(idx, data_batch) File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/runner/loops.py", li ne 128, in run_iter outputs = self.runner.model.train_step( File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/model/wrappers/distr ibuted.py", line 123, in train_step optim_wrapper.update_params(parsed_loss) File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/optim/optimizer/opti mizer_wrapper.py", line 196, in update_params self.backward(loss) File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/optim/optimizer/amp_ optimizer_wrapper.py", line 126, in backward self.loss_scaler.scale(loss).backward(**kwargs) File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/quchunguang/anaconda3/envs/yoloworld/lib/python3.9/site-packages/torch/autograd/**init**.py", line 173, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

分割权重，在镜像网站没找到。只有如下权重。
![1711604887754](https://github.com/AILab-CVC/YOLO-World/assets/32487883/21f0d5a9-d8ec-4206-8ba9-33d390187ced)

源码里面的权重和这个不一样。
