### ISSUE TITLE
run  image_demo.py   on  jetson  

### ISSUE THREAD

**Issue by lfreee** [AILab-CVC/YOLO-World#197]
File "/home/mic-710ailx/miniconda3/envs/yolo/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/mic-710ailx/YOLO-World-master/yolo_world/models/backbones/mm_backbone.py", line 76, in __init__
    self.model = CLIPTP.from_pretrained(model_name, config=clip_config)
  File "/home/mic-710ailx/miniconda3/envs/yolo/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3527, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/mic-710ailx/miniconda3/envs/yolo/lib/python3.8/site-packages/transformers/modeling_utils.py", line 554, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/home/mic-710ailx/YOLO-World-master/pretrained_models/clip-vit-base-patch32/pytorch_model.bin' at '/home/mic-710ailx/YOLO-World-master/pretrained_models/clip-vit-base-patch32/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True

**Comment by wondervictor** [comment]
Hi @lfreee, I suggest that you re-download the checkpoint of CLIP, and this error usually appears due to the incomplete checkpoint file.

**Comment by 3210448723** [comment]
Do I need to re-download the weight file? Where is the path of the weight file?

```bash
FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
Traceback (most recent call last):
  File "/home/user/yuanjinmin/YOLO-World-master/demo/gradio_demo.py", line 243, in <module>
    runner = Runner.from_cfg(cfg)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/user/yuanjinmin/YOLO-World-master/yolo_world/models/detectors/yolo_world.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmyolo/models/detectors/yolo_detector.py", line 41, in __init__
    super().__init__(
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 30, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/user/yuanjinmin/YOLO-World-master/yolo_world/models/backbones/mm_backbone.py", line 190, in __init__
    self.text_model = MODELS.build(text_model)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/user/yuanjinmin/YOLO-World-master/yolo_world/models/backbones/mm_backbone.py", line 76, in __init__
    self.model = CLIPTP.from_pretrained(model_name, config=clip_config)
  File "/home/user/anaconda3/envs/yjm_yolo_world/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3301, in from_pretrained
    raise EnvironmentError(
OSError: openai/clip-vit-base-patch32 does not appear to have a file named pytorch_model.bin but there is a file for TensorFlow weights. Use `from_tf=True` to load this model from those weights.
```
