### ISSUE TITLE
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

### ISSUE THREAD

**Issue by scc103766** [AILab-CVC/YOLO-World#198]
File "D:\YOLO-World\demo.py", line 22, in <module>
    from mmdet.datasets import CocoDataset
  File "D:\envs\lib\site-packages\mmdet\datasets\__init__.py", line 31, in <module>
    from .utils import get_loading_pipeline
  File "D:\envs\lib\site-packages\mmdet\datasets\utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "D:\envs\lib\site-packages\mmdet\datasets\transforms\__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "D:\envs\lib\site-packages\mmdet\datasets\transforms\formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "D:\envs\lib\site-packages\mmdet\structures\bbox\__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "D:\envs\lib\site-packages\mmdet\structures\bbox\base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "D:\envs\lib\site-packages\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "D:\envs\lib\site-packages\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "D:\envs\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\envs\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\envs\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

**Comment by scc103766** [comment]
demo.py 中from mmdet.datasets import CocoDataset 代码没有报错，环境安装应该是没有问题的pip install e.是成功的，运行demo.py时报错。

**Comment by KDGPR** [comment]
+1

**Comment by KDGPR** [comment]
D:\Anaconda\python.exe D:\pythonfile\YOLO-World-master\YOLO-World-master\demo.py 
Traceback (most recent call last):
  File "D:\pythonfile\YOLO-World-master\YOLO-World-master\demo.py", line 22, in <module>
    from mmdet.datasets import CocoDataset
  File "D:\Anaconda\Lib\site-packages\mmdet\datasets\__init__.py", line 31, in <module>
    from .utils import get_loading_pipeline
  File "D:\Anaconda\Lib\site-packages\mmdet\datasets\utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "D:\Anaconda\Lib\site-packages\mmdet\datasets\transforms\__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "D:\Anaconda\Lib\site-packages\mmdet\datasets\transforms\formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "D:\Anaconda\Lib\site-packages\mmdet\structures\bbox\__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "D:\Anaconda\Lib\site-packages\mmdet\structures\bbox\base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "D:\Anaconda\Lib\site-packages\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "D:\Anaconda\Lib\site-packages\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "D:\Anaconda\Lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Anaconda\Lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
                 ^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

Process finished with exit code 1
