### ISSUE TITLE
OSError: Incorrect path_or_model_id: '../pretrained_models/clip-vit-base-patch32-projection'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

### ISSUE THREAD

**Issue by zhujiajian98** [AILab-CVC/YOLO-World#206]
When I used the yolo_world_v2_x_obj365v1_goldg_cc3mlite_pretrain-8698fbfa.pth to infer the image, it would arise the error like this:
```text
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 111, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 159, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../pretrained_models/clip-vit-base-patch32-projection'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "image_demo.py", line 163, in <module>
    runner = Runner.from_cfg(cfg)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zjj/project/YOLO-World/yolo_world/models/detectors/yolo_world.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/home/zjj/project/YOLO-World/third_party/mmyolo/mmyolo/models/detectors/yolo_detector.py", line 41, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 30, in __init__
    self.backbone = MODELS.build(backbone)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zjj/project/YOLO-World/yolo_world/models/backbones/mm_backbone.py", line 190, in __init__
    self.text_model = MODELS.build(text_model)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zjj/project/YOLO-World/yolo_world/models/backbones/mm_backbone.py", line 73, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 779, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 612, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '../pretrained_models/clip-vit-base-patch32-projection'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```
How can I fix the error?

**Comment by mingxingpu** [comment]
you can comment line 18 and uncomment line 19 in your config file.

**Comment by zhujiajian98** [comment]
@mingxingpu Thanks a lot. But when I used the config file and the corresponding weight, I met the next problem like that:
![Screenshot from 2024-04-03 14-06-19](https://github.com/AILab-CVC/YOLO-World/assets/66070217/9ca09036-9f6c-455c-8f13-bf6685be360f)

**Comment by mingxingpu** [comment]
you can try other config file and checkpoint.   the given wieghts of v2_XL is same with v2_X。 That seems a mistake.

**Comment by zhujiajian98** [comment]
Thank you very much, the error has been resolved.
