### ISSUE TITLE
environment problem of run image_demo.py

### ISSUE THREAD

**Issue by scc103766** [AILab-CVC/YOLO-World#218]
Traceback (most recent call last):
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmengine\utils\misc.py", line 78, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "D:\anaconda\envs\yolo_world\lib\importlib\__init__.py", line 128, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\computer_vison\YOLO-World\yolo_world\__init__.py", line 2, in <module>
    from .models import *  # noqa
  File "D:\computer_vison\YOLO-World\yolo_world\models\__init__.py", line 3, in <module>
    from .layers import *  # noqa
  File "D:\computer_vison\YOLO-World\yolo_world\models\layers\__init__.py", line 4, in <module>
    from .yolo_bricks import (
  File "D:\computer_vison\YOLO-World\yolo_world\models\layers\yolo_bricks.py", line 12, in <module>
    from mmyolo.models.layers import CSPLayerWithTwoConv
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmyolo\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmyolo\models\backbones\__init__.py", line 3, in <module>
    from .csp_darknet import YOLOv5CSPDarknet, YOLOv8CSPDarknet, YOLOXCSPDarknet
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmyolo\models\backbones\csp_darknet.py", line 7, in <module>
    from mmdet.models.backbones.csp_darknet import CSPLayer, Focus
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmdet\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmdet\models\backbones\__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmdet\models\backbones\csp_darknet.py", line 11, in <module>
    from ..layers import CSPLayer
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmdet\models\layers\__init__.py", line 3, in <module>
    from .bbox_nms import fast_nms, multiclass_nms
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmdet\models\layers\bbox_nms.py", line 5, in <module>
    from mmcv.ops.nms import batched_nms
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\anaconda\envs\yolo_world\lib\importlib\__init__.py", line 128, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmengine\config\config.py", line 464, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmengine\utils\misc.py", line 85, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import yolo_world

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\computer_vison\YOLO-World\image_demo.py", line 154, in <module>
    cfg = Config.fromfile(args.config)
  File "D:\anaconda\envs\yolo_world\lib\site-packages\mmengine\config\config.py", line 476, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['yolo_world'], 'allow_failed_imports': False}, the current sys.path is:
    D:\computer_vison\YOLO-World
    D:\anaconda\envs\yolo_world\python39.zip
    D:\anaconda\envs\yolo_world\DLLs
    D:\anaconda\envs\yolo_world\lib
    C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages
    D:\anaconda\envs\yolo_world\lib\site-packages
    D:\anaconda\envs\yolo_world\lib\site-packages\win32
    D:\anaconda\envs\yolo_world\lib\site-packages\win32\lib
    D:\anaconda\envs\yolo_world\lib\site-packages\Pythonwin
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

**Comment by scc103766** [comment]
使用python3.9时频繁出错，使用python3.8时没有此问题，推测时环境支持不够完善。
