### ISSUE TITLE
how to fix 'file_client_args' issue

### ISSUE THREAD

**Issue by ForestWang** [AILab-CVC/YOLO-World#221]
python demo.py configs/pretrain/yolo_world_v2_l_clip_large_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_800ft_lvis_minival.py ./weights/YOLO-World/yolo_world_v2_l_clip_large_o365v1_goldg_pretrain_800ft-9df82e55.pth
Traceback (most recent call last):
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/mmengine/config/config.py", line 107, in __getattr__
    value = super().__getattr__(name)
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/mmengine/config/config.py", line 136, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/mmengine/config/config.py", line 103, in __missing__
    raise KeyError(name)
KeyError: 'file_client_args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mi/robotics/YOLO-World/demo.py", line 213, in <module>
    cfg = Config.fromfile(args.config)
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/mmengine/config/config.py", line 457, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/mmengine/config/config.py", line 941, in _file2dict
    raise e
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/mmengine/config/config.py", line 919, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "/home/mi/robotics/YOLO-World/configs/pretrain/yolo_world_v2_l_clip_large_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_800ft_lvis_minival.py", line 134, in <module>
    dict(type='LoadImageFromFile', file_client_args=_base_.file_client_args),
  File "/home/mi/miniconda3/envs/unienv/lib/python3.10/site-packages/mmengine/config/config.py", line 111, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'file_client_args

**Comment by wondervictor** [comment]
Hi @ForestWang, please remove `file_client_args=_base_.file_client_args`
