### ISSUE TITLE
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 25` while installing in Colab

### ISSUE THREAD

**Issue by SkalskiP** [AILab-CVC/YOLO-World#23]
Hi 👋🏻 I was trying to install YOLO-World in Google Colab, but unfortunately, an error appears after executing the `python setup.py build develop` command. [link](https://colab.research.google.com/drive/11dSW8l_dENjk_i6iPvGjbaEjeE6BFeV_?usp=sharing)

```
Installed /usr/local/lib/python3.10/dist-packages/semantic_version-2.10.0-py3.10.egg
Searching for ruff>=0.1.7
Reading https://pypi.org/simple/ruff/
Downloading https://files.pythonhosted.org/packages/07/1e/fa1c65330787f08e73980e8401f7996882f0c556975f0cb31ef742b9908a/ruff-0.2.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=3826fb34c144ef1e171b323ed6ae9146ab76d109960addca730756dc19dc7b22
Best match: ruff 0.2.0
Processing ruff-0.2.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Installing ruff-0.2.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /usr/local/lib/python3.10/dist-packages
Adding ruff 0.2.0 to easy-install.pth file
Traceback (most recent call last):
  File "/content/YOLO-World/setup.py", line 163, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 130, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 750, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1133, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1145, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 677, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 705, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 731, in process_distribution
    self.install_egg_scripts(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 152, in install_egg_scripts
    return easy_install.install_egg_scripts(self, dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 607, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1519, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 25: invalid start byte in scripts/ruff file at path: /usr/local/lib/python3.10/dist-packages/ruff-0.2.0-py3.10-linux-x86_64.egg/EGG-INFO/scripts/ruff
```

**Comment by shadowofsoul** [comment]
Same here not in colab, but in a VM with a L4 GPU. And trynig to install it via pip gives me:

```
Traceback (most recent call last):
  File "/home/shadow_of_soul08/yolow/lib/python3.10/site-packages/torch-2.2.0-py3.10-linux-x86_64.egg/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shadow_of_soul08/YOLO-World/export.py", line 5, in <module>
    import torch
  File "/home/shadow_of_soul08/yolow/lib/python3.10/site-packages/torch-2.2.0-py3.10-linux-x86_64.egg/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/home/shadow_of_soul08/yolow/lib/python3.10/site-packages/torch-2.2.0-py3.10-linux-x86_64.egg/torch/__init__.py", line 197, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/shadow_of_soul08/yolow/lib/python3.10/site-packages/torch-2.2.0-py3.10-linux-x86_64.egg/torch/__init__.py", line 163, in _preload_cuda_deps
    ctypes.CDLL(lib_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvJitLink.so.12: cannot open shared object file: No such file or directory

**Comment by abhimnc** [comment]
i am also getting same error while installing on colab and my local machine both.
running build
running build_py
creating build
creating build/lib
creating build/lib/yolo_world
copying yolo_world/__init__.py -> build/lib/yolo_world
copying yolo_world/version.py -> build/lib/yolo_world
creating build/lib/yolo_world/datasets
copying yolo_world/datasets/__init__.py -> build/lib/yolo_world/datasets
copying yolo_world/datasets/yolov5_obj365v2.py -> build/lib/yolo_world/datasets
copying yolo_world/datasets/yolov5_obj365v1.py -> build/lib/yolo_world/datasets
copying yolo_world/datasets/utils.py -> build/lib/yolo_world/datasets
copying yolo_world/datasets/yolov5_mixed_grounding.py -> build/lib/yolo_world/datasets
copying yolo_world/datasets/yolov5_v3det.py -> build/lib/yolo_world/datasets
copying yolo_world/datasets/mm_dataset.py -> build/lib/yolo_world/datasets
copying yolo_world/datasets/yolov5_lvis.py -> build/lib/yolo_world/datasets
creating build/lib/yolo_world/models
copying yolo_world/models/__init__.py -> build/lib/yolo_world/models
creating build/lib/yolo_world/engine
copying yolo_world/engine/__init__.py -> build/lib/yolo_world/engine
creating build/lib/yolo_world/datasets/transformers
copying yolo_world/datasets/transformers/mm_transforms.py -> build/lib/yolo_world/datasets/transformers
copying yolo_world/datasets/transformers/mm_mix_img_transforms.py -> build/lib/yolo_world/datasets/transformers
copying yolo_world/datasets/transformers/__init__.py -> build/lib/yolo_world/datasets/transformers
creating build/lib/yolo_world/models/layers
copying yolo_world/models/layers/__init__.py -> build/lib/yolo_world/models/layers
copying yolo_world/models/layers/yolo_bricks.py -> build/lib/yolo_world/models/layers
creating build/lib/yolo_world/models/necks
copying yolo_world/models/necks/yolo_world_pafpn.py -> build/lib/yolo_world/models/necks
copying yolo_world/models/necks/__init__.py -> build/lib/yolo_world/models/necks
creating build/lib/yolo_world/models/backbones
copying yolo_world/models/backbones/__init__.py -> build/lib/yolo_world/models/backbones
copying yolo_world/models/backbones/mm_backbone.py -> build/lib/yolo_world/models/backbones
creating build/lib/yolo_world/models/data_preprocessors
copying yolo_world/models/data_preprocessors/data_preprocessor.py -> build/lib/yolo_world/models/data_preprocessors
copying yolo_world/models/data_preprocessors/__init__.py -> build/lib/yolo_world/models/data_preprocessors
creating build/lib/yolo_world/models/dense_heads
copying yolo_world/models/dense_heads/__init__.py -> build/lib/yolo_world/models/dense_heads
copying yolo_world/models/dense_heads/yolo_world_head.py -> build/lib/yolo_world/models/dense_heads
creating build/lib/yolo_world/models/detectors
copying yolo_world/models/detectors/__init__.py -> build/lib/yolo_world/models/detectors
copying yolo_world/models/detectors/yolo_world.py -> build/lib/yolo_world/models/detectors
creating build/lib/yolo_world/models/losses
copying yolo_world/models/losses/dynamic_loss.py -> build/lib/yolo_world/models/losses
copying yolo_world/models/losses/__init__.py -> build/lib/yolo_world/models/losses
creating build/lib/yolo_world/engine/optimizers
copying yolo_world/engine/optimizers/__init__.py -> build/lib/yolo_world/engine/optimizers
copying yolo_world/engine/optimizers/yolow_v5_optim_constructor.py -> build/lib/yolo_world/engine/optimizers
running egg_info
creating yolo_world.egg-info
writing yolo_world.egg-info/PKG-INFO
writing dependency_links to yolo_world.egg-info/dependency_links.txt
writing requirements to yolo_world.egg-info/requires.txt
writing top-level names to yolo_world.egg-info/top_level.txt
writing manifest file 'yolo_world.egg-info/SOURCES.txt'
reading manifest file 'yolo_world.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'yolo_world.egg-info/SOURCES.txt'
running develop
/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running build_ext
Creating /usr/local/lib/python3.10/dist-packages/yolo-world.egg-link (link to .)
Adding yolo-world 0.1.0 to easy-install.pth file

Installed /content/YOLO-World
Processing dependencies for yolo-world==0.1.0
Searching for pot
Reading https://pypi.org/simple/pot/
Downloading https://files.pythonhosted.org/packages/71/9f/ea12f9cec44bf5101cfe34905875adbfc0d665ec6630dc7f0e320f249ef2/POT-0.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=dfaf40a74c5131c1c49f5624c170cb4de24f294ddef1cff6c494321c134d6f2d
Best match: POT 0.9.3
Processing POT-0.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Installing POT-0.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /usr/local/lib/python3.10/dist-packages
Adding POT 0.9.3 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/POT-0.9.3-py3.10-linux-x86_64.egg
Searching for ftfy
Reading https://pypi.org/simple/ftfy/
Downloading https://files.pythonhosted.org/packages/91/f8/dfa32d06cfcbdb76bc46e0f5d69c537de33f4cedb1a15cd4746ab45a6a26/ftfy-6.1.3-py3-none-any.whl#sha256=e49c306c06a97f4986faa7a8740cfe3c13f3106e85bcec73eb629817e671557c
Best match: ftfy 6.1.3
Processing ftfy-6.1.3-py3-none-any.whl
Installing ftfy-6.1.3-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding ftfy 6.1.3 to easy-install.pth file
Installing ftfy script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/ftfy-6.1.3-py3.10.egg
Searching for supervision==0.18.0
Reading https://pypi.org/simple/supervision/
Downloading https://files.pythonhosted.org/packages/53/f7/490cf47d2141f5cc8eeb944b90108cdea5ccfcd100fd6f669bc86cfb6278/supervision-0.18.0-py3-none-any.whl#sha256=78d05e91c8c2fd605a8c04a0fc6073bdce9eb3cbd3300c2badbe6868e7964804
Best match: supervision 0.18.0
Processing supervision-0.18.0-py3-none-any.whl
Installing supervision-0.18.0-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding supervision 0.18.0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/supervision-0.18.0-py3.10.egg
Searching for yapf
Reading https://pypi.org/simple/yapf/
Downloading https://files.pythonhosted.org/packages/66/c9/d4b03b2490107f13ebd68fe9496d41ae41a7de6275ead56d0d4621b11ffd/yapf-0.40.2-py3-none-any.whl#sha256=adc8b5dd02c0143108878c499284205adb258aad6db6634e5b869e7ee2bd548b
Best match: yapf 0.40.2
Processing yapf-0.40.2-py3-none-any.whl
Installing yapf-0.40.2-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding yapf 0.40.2 to easy-install.pth file
Installing yapf script to /usr/local/bin
Installing yapf-diff script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/yapf-0.40.2-py3.10.egg
Searching for addict
Reading https://pypi.org/simple/addict/
Downloading https://files.pythonhosted.org/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl#sha256=249bb56bbfd3cdc2a004ea0ff4c2b6ddc84d53bc2194761636eb314d5cfa5dfc
Best match: addict 2.4.0
Processing addict-2.4.0-py3-none-any.whl
Installing addict-2.4.0-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding addict 2.4.0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/addict-2.4.0-py3.10.egg
Searching for gradio
Reading https://pypi.org/simple/gradio/
Downloading https://files.pythonhosted.org/packages/1f/2d/225bc5f6dd1fbee4fa4852eba8a319b56d1a7fd8be91c059384f4593249f/gradio-4.17.0-py3-none-any.whl#sha256=066012ffd0747e87fa8cde4409d73fb6a71a6aaba881e5348fa119a1ff1cdfcc
Best match: gradio 4.17.0
Processing gradio-4.17.0-py3-none-any.whl
Installing gradio-4.17.0-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding gradio 4.17.0 to easy-install.pth file
Installing gradio script to /usr/local/bin
Installing upload_theme script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/gradio-4.17.0-py3.10.egg
Searching for mmyolo
Reading https://pypi.org/simple/mmyolo/
Downloading https://files.pythonhosted.org/packages/b9/c0/83de140445618b07aaeca65cefbc2be158d4a4bc914d2040a81ad8083537/mmyolo-0.6.0-py3-none-any.whl#sha256=fc6eac828cfecb43ad3c3b7d39f50c79cacbd894e78fe1ac9bd3c8c4eebc659d
Best match: mmyolo 0.6.0
Processing mmyolo-0.6.0-py3-none-any.whl
Installing mmyolo-0.6.0-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding mmyolo 0.6.0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/mmyolo-0.6.0-py3.10.egg
Searching for mmdet
Reading https://pypi.org/simple/mmdet/
Downloading https://files.pythonhosted.org/packages/02/c7/c2d91161c9b3e1c237ea00e9cefb7f4bfe2854769f56025db415b734aedb/mmdet-3.3.0-py3-none-any.whl#sha256=2e23e291281ac57e7dccf8678e957da45fbe560ce78a1f5ded6afeccd3730f17
Best match: mmdet 3.3.0
Processing mmdet-3.3.0-py3-none-any.whl
Installing mmdet-3.3.0-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding mmdet 3.3.0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/mmdet-3.3.0-py3.10.egg
Searching for openmim
Reading https://pypi.org/simple/openmim/
Downloading https://files.pythonhosted.org/packages/00/b3/95531cee452028869d0e08974561f83e9c256c98f62c7a45a51893a61c54/openmim-0.3.9-py2.py3-none-any.whl#sha256=71581498b68767f8e1f340575b91c9994ccc93656901639f11300e46247da263
Best match: openmim 0.3.9
Processing openmim-0.3.9-py2.py3-none-any.whl
Installing openmim-0.3.9-py2.py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding openmim 0.3.9 to easy-install.pth file
Installing mim script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/openmim-0.3.9-py3.10.egg
Searching for uvicorn>=0.14.0
Reading https://pypi.org/simple/uvicorn/
Downloading https://files.pythonhosted.org/packages/c7/f3/29caa83f5795b20ed3aca357c648f3ae995ff6ff08e38b22387017abbdc5/uvicorn-0.27.0.post1-py3-none-any.whl#sha256=4b85ba02b8a20429b9b205d015cbeb788a12da527f731811b643fd739ef90d5f
Best match: uvicorn 0.27.0.post1
Processing uvicorn-0.27.0.post1-py3-none-any.whl
Installing uvicorn-0.27.0.post1-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding uvicorn 0.27.0.post1 to easy-install.pth file
Installing uvicorn script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/uvicorn-0.27.0.post1-py3.10.egg
Searching for tomlkit==0.12.0
Reading https://pypi.org/simple/tomlkit/
Downloading https://files.pythonhosted.org/packages/68/4f/12207897848a653d03ebbf6775a29d949408ded5f99b2d87198bc5c93508/tomlkit-0.12.0-py3-none-any.whl#sha256=926f1f37a1587c7a4f6c7484dae538f1345d96d793d9adab5d3675957b1d0766
Best match: tomlkit 0.12.0
Processing tomlkit-0.12.0-py3-none-any.whl
Installing tomlkit-0.12.0-py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding tomlkit 0.12.0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/tomlkit-0.12.0-py3.10.egg
Searching for semantic-version~=2.0
Reading https://pypi.org/simple/semantic-version/
Downloading https://files.pythonhosted.org/packages/6a/23/8146aad7d88f4fcb3a6218f41a60f6c2d4e3a72de72da1825dc7c8f7877c/semantic_version-2.10.0-py2.py3-none-any.whl#sha256=de78a3b8e0feda74cabc54aab2da702113e33ac9d9eb9d2389bcf1f58b7d9177
Best match: semantic-version 2.10.0
Processing semantic_version-2.10.0-py2.py3-none-any.whl
Installing semantic_version-2.10.0-py2.py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding semantic-version 2.10.0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/semantic_version-2.10.0-py3.10.egg
Searching for ruff>=0.1.7
Reading https://pypi.org/simple/ruff/
Downloading https://files.pythonhosted.org/packages/70/d3/67fdaff63c3092fb667573d6b69fe601020212078b68adedcb821ad4dfcd/ruff-0.2.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=f3ef052283da7dec1987bba8d8733051c2325654641dfe5877a4022108098683
Best match: ruff 0.2.1
Processing ruff-0.2.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Installing ruff-0.2.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /usr/local/lib/python3.10/dist-packages
Adding ruff 0.2.1 to easy-install.pth file
Traceback (most recent call last):
  File "/content/YOLO-World/setup.py", line 163, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 130, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 750, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1133, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1145, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 677, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 705, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 731, in process_distribution
    self.install_egg_scripts(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 152, in install_egg_scripts
    return easy_install.install_egg_scripts(self, dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 607, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1519, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte in scripts/ruff file at path: /usr/local/lib/python3.10/dist-packages/ruff-0.2.1-py3.10-linux-x86_64.egg/EGG-INFO/scripts/ruff

**Comment by abhimnc** [comment]
Just run the command another time. It worked. I don't why.

**Comment by Penterakt** [comment]
I have the same problem. Reruning the command doesn't help.

`Using /home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/semantic_version-2.10.0-py3.9.egg
Searching for ruff==0.2.1
Best match: ruff 0.2.1
Processing ruff-0.2.1-py3.9-linux-x86_64.egg
Adding ruff 0.2.1 to easy-install.pth file
Traceback (most recent call last):
  File "/home/yunnan/repos/YOLO-World/setup.py", line 163, in <module>
    setup(
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/develop.py", line 124, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 799, in process_distribution
    self.easy_install(dist.as_requirement())
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 713, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 743, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 770, in process_distribution
    self.install_egg_scripts(dist)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/develop.py", line 146, in install_egg_scripts
    return easy_install.install_egg_scripts(self, dist)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 640, in install_egg_scripts
    dist, script_name, dist.get_metadata('scripts/' + script_name)
  File "/home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1521, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte in scripts/ruff file at path: /home/yunnan/anaconda3/envs/yolo_world/lib/python3.9/site-packages/ruff-0.2.1-py3.9-linux-x86_64.egg/EGG-INFO/scripts/ruff
`

**Comment by huzhangcs** [comment]
i use pip install -e . instead of python setup.py build develop and resolve the problem.

**Comment by huzhangcs** [comment]
@SkalskiP I have tried. It works well for me and i can import the mmengine package. May i know what version do you install?

**Comment by SkalskiP** [comment]
This is what I do right now:

```
!git clone https://github.com/AILab-CVC/YOLO-World.git
%cd YOLO-World

%pip install -U -q openmim
!pip install mmcv==2.0.1 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html -q
!mim install -q 'mmengine>=0.6.0'
!mim install -q 'mmdet>=3.0.0,<4.0.0'
!mim install -q 'mmyolo'
!pip install -e . -q

!mkdir -p third_party
%cd third_party
!git clone https://github.com/open-mmlab/mmyolo.git

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
