### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Amas-Hu** [AILab-CVC/YOLO-World#233]
这是为什么
Traceback (most recent call last):
  File "C:\Files\PythonFiles\YOLO-World\demo.py", line 210, in <module>
    args = parse_args()
  File "C:\Files\PythonFiles\YOLO-World\demo.py", line 51, in parse_args
    args = parser.parse_args()
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 1825, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 2095, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 2580, in error
    self.print_usage(_sys.stderr)
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 2550, in print_usage
    self._print_message(self.format_usage(), file)
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 2516, in format_usage
    return formatter.format_help()
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\argparse.py", line 339, in _format_usage
    assert ' '.join(pos_parts) == pos_usage
AssertionError

**Comment by Amas-Hu** [comment]
跑demo.py遇到的

**Comment by Amas-Hu** [comment]
> @Amas-Hu 你好，请提供完整的命令
你好，我把demo.py改了这两行，然后运行报错了
 parser.add_argument('configs/finetune_coco/yolo_world_l_dual_vlpan_2e-4_80e_8gpus_finetune_coco.py ', help='test config file path')
    parser.add_argument('weights/yolo_world_v2_s_vlpan_bn_2e-4_80e_8gpus_mask-refine_finetune_coco_ep80-492dc329.pth', help='checkpoint file')
