### ISSUE TITLE
demo.pyWhen I run the demo. py code, AttributeError appears: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by jolinfs** [AILab-CVC/YOLO-World#234]
Why does this problem occur? AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by wondervictor** [comment]
Hi @jolinfs, please provide your running script.

**Comment by jolinfs** [comment]
`(yolo_world) D:\paper\detect\YOLO-World-master>python demo.py
Traceback (most recent call last):
  File "D:\paper\detect\YOLO-World-master\demo.py", line 212, in <module>
    cfg = Config.fromfile(args.config)
  File "D:\ProgramData\anaconda3\envs\yolo_world\lib\site-packages\mmengine\config\config.py", line 458, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
  File "D:\ProgramData\anaconda3\envs\yolo_world\lib\site-packages\mmengine\config\config.py", line 1655, in _is_lazy_import
    if not filename.endswith('.py'):
AttributeError: 'NoneType' object has no attribute 'endswith'
`

**Comment by wondervictor** [comment]
Hi @jolinfs, you should check whether you run the script correctly.
