### ISSUE TITLE
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

### ISSUE THREAD

**Issue by Amas-Hu** [AILab-CVC/YOLO-World#268]
命令：python demo.py configs/pretrain/yolo_world_l_t2i_bn_2e-4_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py pretrained_weights/yolow-v8_l_clipv2_frozen_t2iv2_bn_o365_goldg_pretrain.pth
报错：Traceback (most recent call last):
  File "C:\Files\PythonFiles\YOLO-World\demo.py", line 22, in <module>
    from mmdet.datasets import CocoDataset
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\datasets\__init__.py", line 14, in <module>
    from .utils import get_loading_pipeline
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\datasets\utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\datasets\transforms\__init__.py", line 6, in <module>
    from .formatting import ImageToTensor, PackDetInputs, ToTensor, Transpose
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\datasets\transforms\formatting.py", line 9, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\structures\bbox\__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\structures\bbox\base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\hu\anaconda3\envs\yolo-world\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

**Comment by LittleFighterT** [comment]
你需要先安装torch的GPU版本  
!pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
  !pip install requests==2.28.2 tqdm==4.65.0 rich==13.4.2
  %pip install -U openmim
  !mim install "mmengine>=0.7.0"
  !mim install "mmcv"
然后再安装yolo-world
pip install -e . -vv

**Comment by tomgotjack** [comment]
我遇到过同样问题，重新配环境解决了。
先装GPU版torch，然后手动安装MMlab相关包。不要直接使用 pip install -e . 
使用pip install -e .安装时不会报错，但运行时就产生了ext: 找不到指定的程序报错。
我查了一下似乎MMCV还是啥和torch有对应关系，严格按照安装顺序来似乎可以解决问题。
