### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x768 and 512x320)

### ISSUE THREAD

**Issue by YU-FAITH** [AILab-CVC/YOLO-World#281]
**this is my config:** 
args.config = "configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py"
args.checkpoint = "./yolo_world_v2_x_obj365v1_goldg_cc3mlite_pretrain-8698fbfa.pth"
args.text = 'person,dog,cat,'
args.output_dir = "./show_dets"

**but got a error:**
size mismatch for backbone.text_model.model.text_model.encoder.layers.11.mlp.fc2.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
size mismatch for backbone.text_model.model.text_model.encoder.layers.11.layer_norm2.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
size mismatch for backbone.text_model.model.text_model.encoder.layers.11.layer_norm2.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
size mismatch for backbone.text_model.model.text_model.final_layer_norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
size mismatch for backbone.text_model.model.text_model.final_layer_norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
size mismatch for backbone.text_model.model.text_projection.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([768, 768]).
04/26 12:35:49 - mmengine - INFO - Load checkpoint from ./yolo_world_v2_x_obj365v1_goldg_cc3mlite_pretrain-8698fbfa.pth
[                                                  ] 0/149, elapsed: 0s, ETA:Traceback (most recent call last):
  File "image_demo.py", line 200, in <module>
    inference_detector(runner,
  File "image_demo.py", line 85, in inference_detector
    output = runner.model.test_step(data_batch)[0]
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "/nas/users/perception-users/jinchuan/public_github/YOLO-World/yolo_world/models/detectors/yolo_world.py", line 43, in predict
    img_feats, txt_feats = self.extract_feat(batch_inputs,
  File "/nas/users/perception-users/jinchuan/public_github/YOLO-World/yolo_world/models/detectors/yolo_world.py", line 98, in extract_feat
    img_feats = self.neck(img_feats, txt_feats)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/users/perception-users/jinchuan/public_github/YOLO-World/yolo_world/models/necks/yolo_world_pafpn.py", line 127, in forward
    inner_out = self.top_down_layers[len(self.in_channels) - 1 - idx](
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/users/perception-users/jinchuan/public_github/YOLO-World/yolo_world/models/layers/yolo_bricks.py", line 150, in forward
    x_main.append(self.attn_block(x_main[-1], guide))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/users/perception-users/jinchuan/public_github/YOLO-World/yolo_world/models/layers/yolo_bricks.py", line 71, in forward
    guide = self.guide_fc(guide)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/cnn/bricks/wrappers.py", line 177, in forward
    return super().forward(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
**RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x768 and 512x320)**

**this is pretrain model folder:**
![image](https://github.com/AILab-CVC/YOLO-World/assets/20354847/867db0f2-b74d-4960-acbc-525fa30d5d90)

@wondervictor **help me please!!!!**

**Comment by wondervictor** [comment]
using `openai/clip-vit-base-patch32` please.
