### ISSUE TITLE
mmdet.CocoMetric problem

### ISSUE THREAD

**Issue by taofuyu** [AILab-CVC/YOLO-World#286]
Anyone meets this problem ?
When computing metric of type `MultiModalDataset` using mmdet.CocoMetric, like COCO val2017 or custom close-set dataset, it will report errors:

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.97902
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 1.00000
Traceback (most recent call last):
  File "tools/test.py", line 150, in <module>
    main()
  File "tools/test.py", line 146, in main
    runner.test()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 1823, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 448, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmdet/evaluation/metrics/coco_metric.py", line 519, in compute_metrics
    coco_eval.summarize()
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 518, in summarize
    self.stats = summarize()
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 487, in _summarizeDets
    stats[2] = _summarize(1, iouThr=.75, maxDets=self.params.maxDets[2])
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 468, in _summarize
    s = s[:,:,:,t,:]
IndexError: index 5 is out of bounds for axis 3 with size 4

`The first is AP will be very high, second is this IndexError.`

I just run like this:
python tools/test.py  configs/finetune_coco/a_offical_config.py  path/to/offical_weights.pth

**Comment by wondervictor** [comment]
Hi @taofuyu, could you share the config about `evaluation metric`? It might need to modify some items for custom datasets.

**Comment by taofuyu** [comment]
It is COCO dataste, I  use this `[config](https://github.com/AILab-CVC/YOLO-World/blob/b211ae776658de2d8a828db202bd4a7c445e4f12/configs/finetune_coco/yolo_world_v2_s_vlpan_bn_2e-4_80e_8gpus_mask-refine_finetune_coco.py#L9)`
I just  replace  image root

**Comment by wondervictor** [comment]
Hi @taofuyu, have you modified `pycocotools`?

**Comment by taofuyu** [comment]
Hi，I dont modify anything except image_root and anno_file's path

**Comment by wondervictor** [comment]
1. This version of `cocoeval` differs from the official version (https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py)
2. It seems that `t` is out of bounds while `t` represents different thresholds.： https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L450

You might specify the thresholds:
1. `mmdet.COCOMetric`: https://github.com/open-mmlab/mmdetection/blob/cfd5d3a985b0249de009b67d04f37263e11cdf3d/mmdet/evaluation/metrics/coco_metric.py#L75
2. `pycocotools`: https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L502

**Comment by taofuyu** [comment]
Thanks.  I solve this by  re-installing pycocotools==2.0.7
