### ISSUE TITLE
运行video_demo.py

### ISSUE THREAD

**Issue by Amas-Hu** [AILab-CVC/YOLO-World#308]

**Comment by Amas-Hu** [comment]
配置：../configs/pretrain_v1/yolo_world_s_dual_vlpan_l2norm_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py
../configs/pretrain_v1/yolo_world_s_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-18bea4d2.pth
'person,car'
./sample_video/jiejing.mp4

报错：C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
{'type': 'ImagePoolingAttentionModule', 'embed_channels': 256, 'num_heads': 8, 'image_channels': [128, 256, 512], 'text_channels': 512, 'num_feats': 3}
Loads checkpoint by local backend from path: ../configs/pretrain_v1/yolo_world_s_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-18bea4d2.pth
Traceback (most recent call last):
  File "C:\Files\PythonFiles\YOLO-World4.28\demo\video_demo.py", line 108, in <module>
    main()
  File "C:\Files\PythonFiles\YOLO-World4.28\demo\video_demo.py", line 55, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmdet\apis\inference.py", line 102, in init_detector
    metainfo = DATASETS.build(test_dataset_cfg).metainfo
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\Files\PythonFiles\YOLO-World4.28\yolo_world\datasets\mm_dataset.py", line 25, in __init__
    self.dataset = DATASETS.build(dataset)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmyolo\datasets\yolov5_coco.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmdet\datasets\base_det_dataset.py", line 51, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmengine\dataset\base_dataset.py", line 247, in __init__
    self.full_init()
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmyolo\datasets\yolov5_coco.py", line 27, in full_init
    self.data_list = self.load_data_list()
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\mmdet\datasets\lvis.py", line 605, in load_data_list
    self.lvis = LVIS(local_path)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\lvis\lvis.py", line 27, in __init__
    self.dataset = self._load_json(annotation_path)
  File "C:\Users\hu\anaconda3\envs\yolo-worldpy3.10\lib\site-packages\lvis\lvis.py", line 35, in _load_json
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/lvis/lvis_v1_minival_inserted_image_name.json'

**Comment by wondervictor** [comment]
Hi @Amas-Hu, you need to add the `lvis_v1_minival_inserted_image_name.json` and you can find it at https://huggingface.co/GLIPModel/GLIP/blob/main/lvis_v1_minival_inserted_image_name.json

I'll remove it for smooth inference later.
