### ISSUE TITLE
Value error in albumentations

### ISSUE THREAD

**Issue by XieKaiwen** [AILab-CVC/YOLO-World#343]
Brief Context: I am trying to finetune yoloworld on open-set detection and my dataset is already formatted in a Mixed Grounding dataset format. But I have ran into an error while running the training CLI, the error is related to a key mismatch (i guess) when the script runs through albumentations.

![Screenshot 2024-05-23 133910](https://github.com/AILab-CVC/YOLO-World/assets/122254712/153ccd4d-2fe1-454b-a962-b41b5ce55273)
![image](https://github.com/AILab-CVC/YOLO-World/assets/122254712/214040b0-0ad5-4d91-9cc3-c137a2b0c77b)

The error received is:

```
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 410, in __getitem__
[rank0]:     data = self.prepare_data(idx)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmyolo/datasets/yolov5_coco.py", line 53, in prepare_data
[rank0]:     return self.pipeline(data_info)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmcv/transforms/base.py", line 12, in __call__
[rank0]:     return self.transform(results)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmcv/transforms/wrappers.py", line 88, in transform
[rank0]:     results = t(results)  # type: ignore
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmcv/transforms/base.py", line 12, in __call__
[rank0]:     return self.transform(results)
[rank0]:   File "/home/jupyter/til-24-base/vlm/mmdetection/mmdet/structures/bbox/box_type.py", line 267, in wrapper
[rank0]:     return func(self, results)
[rank0]:   File "/home/jupyter/til-24-base/vlm/mmdetection/mmdet/datasets/transforms/transforms.py", line 1699, in transform
[rank0]:     results = self.aug(**results)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/albumentations/core/composition.py", line 248, in __call__
[rank0]:     self._check_args(**data)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/albumentations/core/composition.py", line 319, in _check_args
[rank0]:     raise ValueError(msg)
[rank0]: ValueError: Key img_path is not in available keys.
```
More details are given below... thanks for reading

Below is my code in the config file i used in the training CLI, I commented out all of the code relating to validation and test data because I only have training data in the form of Mixed Grounding data:
```
_base_ = ('../third_party/mmyolo/configs/yolov8/yolov8_l_syncbn_fast_8xb16-500e_coco.py')
custom_imports = dict(
    imports=['yolo_world'],
    allow_failed_imports=False)

# hyper-parameters
num_classes = 80
num_training_classes = 80
max_epochs = 10  # Maximum training epochs
close_mosaic_epochs = 10
save_epoch_intervals = 1
text_channels = 512
neck_embed_channels = [128, 256, _base_.last_stage_out_channels // 2]
neck_num_heads = [4, 8, _base_.last_stage_out_channels // 2 // 32]
base_lr = 2e-4
weight_decay = 0.05
train_batch_size_per_gpu = 8
load_from='pretrained_models/yolo_world_v2_l_obj365v1_goldg_pretrain_1280ft-9babe3f6.pth'
persistent_workers = False

# model settings
model = dict(
    type='YOLOWorldDetector',
    mm_neck=True,
    num_train_classes=num_training_classes,
    num_test_classes=num_classes,
    data_preprocessor=dict(type='YOLOWDetDataPreprocessor'),
    backbone=dict(
        _delete_=True,
        type='MultiModalYOLOBackbone',
        image_model={{_base_.model.backbone}},
        text_model=dict(
            type='HuggingCLIPLanguageBackbone',
            model_name='openai/clip-vit-base-patch32',
            frozen_modules=['all'])),
    neck=dict(type='YOLOWorldDualPAFPN',
              guide_channels=text_channels,
              embed_channels=neck_embed_channels,
              num_heads=neck_num_heads,
              block_cfg=dict(type='MaxSigmoidCSPLayerWithTwoConv'),
              text_enhancder=dict(type='ImagePoolingAttentionModule',
                                  embed_channels=256,
                                  num_heads=8)),
    bbox_head=dict(type='YOLOWorldHead',
                   head_module=dict(type='YOLOWorldHeadModule',
                                    embed_dims=text_channels,
                                    num_classes=num_training_classes)),
    train_cfg=dict(assigner=dict(num_classes=num_training_classes)))

# dataset settings
text_transform = [
    dict(type='RandomLoadText',
         num_neg_samples=(num_classes, num_classes),
         max_num_samples=num_training_classes,
         padding_to_max=True,
         padding_value=''),
    dict(type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'flip',
                    'flip_direction', 'texts'))
]
mosaic_affine_transform = [
    dict(
        type='MultiModalMosaic',
        img_scale=_base_.img_scale,
        pad_val=114.0,
        pre_transform=_base_.pre_transform),
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        max_aspect_ratio=100.,
        scaling_ratio_range=(1 - _base_.affine_scale,
                             1 + _base_.affine_scale),
        # img_scale is (width, height)
        border=(-_base_.img_scale[0] // 2, -_base_.img_scale[1] // 2),
        border_val=(114, 114, 114))
]
train_pipeline = [
    *_base_.pre_transform,
    *mosaic_affine_transform,
    dict(
        type='YOLOv5MultiModalMixUp',
        prob=_base_.mixup_prob,
        pre_transform=[*_base_.pre_transform,
                       *mosaic_affine_transform]),
    *_base_.last_transform[:-1],
    *text_transform
]
train_pipeline_stage2 = [
    *_base_.train_pipeline_stage2[:-1],
    *text_transform
]
vlm_train_dataset = dict(type='YOLOv5MixedGroundingDataset',
                        data_root='augmented_yolo_train_dataset/',
                        ann_file='annotations/yolo_world_train.json',
                        data_prefix=dict(img='images/'),
                        filter_cfg=dict(filter_empty_gt=False, min_size=32),
                        pipeline=train_pipeline)

train_dataloader = dict(
    persistent_workers=persistent_workers,
    batch_size=train_batch_size_per_gpu,
    collate_fn=dict(type='yolow_collate'),
    dataset=vlm_train_dataset)
# test_pipeline = [
#     *_base_.test_pipeline[:-1],
#     dict(type='LoadText'),
#     dict(
#         type='mmdet.PackDetInputs',
#         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
#                    'scale_factor', 'pad_param', 'texts'))
# ]
# coco_val_dataset = dict(
#     _delete_=True,
#     type='MultiModalDataset',
#     dataset=dict(
#         type='YOLOv5CocoDataset',
#         data_root='data/coco',
#         ann_file='annotations/instances_val2017.json',
#         data_prefix=dict(img='val2017/'),
#         filter_cfg=dict(filter_empty_gt=False, min_size=32)),
#     class_text_path='data/texts/coco_class_texts.json',
#     pipeline=test_pipeline)
# val_dataloader = dict(dataset=coco_val_dataset)
# test_dataloader = val_dataloader

#training settings
default_hooks = dict(
    param_scheduler=dict(
        scheduler_type='linear',
        lr_factor=0.01,
        max_epochs=max_epochs),
    checkpoint=dict(
        max_keep_ckpts=-1,
        save_best=None,
        interval=save_epoch_intervals))
custom_hooks = [
    dict(
        type='EMAHook',
        ema_type='ExpMomentumEMA',
        momentum=0.0001,
        update_buffers=True,
        strict_load=False,
        priority=49),
    dict(
        type='mmdet.PipelineSwitchHook',
        switch_epoch=max_epochs - close_mosaic_epochs,
        switch_pipeline=train_pipeline_stage2)
]
train_cfg = dict(
    max_epochs=max_epochs,
    val_interval=20,
    dynamic_intervals=[((max_epochs - close_mosaic_epochs),
                        _base_.val_interval_stage2)])
optim_wrapper = dict(
    optimizer=dict(
        _delete_=True,
        type='AdamW',
        lr=base_lr,
        weight_decay=weight_decay,
        batch_size_per_gpu=train_batch_size_per_gpu),
    paramwise_cfg=dict(
        custom_keys={'backbone.text_model': dict(lr_mult=0.01),
                     'logit_scale': dict(weight_decay=0.0)}),
    constructor='YOLOWv5OptimizerConstructor')

#evaluation settings
# val_evaluator = dict(
#     _delete_=True,
#     type='mmdet.CocoMetric',
#     proposal_nums=(100, 1, 10),
#     ann_file='data/coco/annotations/instances_val2017.json',
#     metric='bbox')
```
I also had to edit the _base_ config file which goes all the way to the yolov8_s_syncbn_fast_8xb16-500e_coco.py, and I editted into the code below. I removed the transforms because my dataset were already augmented (hence the empty list in albu_train_transforms) and also the validation/test code for reasons above.
```
_base_ = ['../_base_/default_runtime.py', '../_base_/det_p5_tta.py']

# ========================Frequently modified parameters======================
# -----data related-----
data_root = 'augmented_yolo_train_dataset/'  # Root path of data
# Path of train annotation file
train_ann_file = 'annotations/yolo_world_train.json'
train_data_prefix = 'images/'  # Prefix of train image path
# Path of val annotation file
# val_ann_file = 'annotations/instances_val2017.json'
# val_data_prefix = 'val2017/'  # Prefix of val image path

num_classes = 80  # Number of classes for classification
# Batch size of a single GPU during training
train_batch_size_per_gpu = 8
# Worker to pre-fetch data for each single GPU during training
train_num_workers = 8
# persistent_workers must be False if num_workers is 0
persistent_workers = True

# -----train val related-----
# Base learning rate for optim_wrapper. Corresponding to 8xb16=64 bs
base_lr = 0.01
max_epochs = 10  # Maximum training epochs
# Disable mosaic augmentation for final 10 epochs (stage 2)
close_mosaic_epochs = 10

model_test_cfg = dict(
    # The config of multi-label for multi-class prediction.
    multi_label=True,
    # The number of boxes before NMS
    nms_pre=30000,
    score_thr=0.001,  # Threshold to filter out boxes.
    nms=dict(type='nms', iou_threshold=0.7),  # NMS type and threshold
    max_per_img=300)  # Max number of detections of each image

# ========================Possible modified parameters========================
# -----data related-----
img_scale = (1520, 870)  # width, height
# Dataset type, this will be used to define the dataset
dataset_type = 'YOLOv5MixedGroundingDataset'
# Batch size of a single GPU during validation
# val_batch_size_per_gpu = 1
# # Worker to pre-fetch data for each single GPU during validation
# val_num_workers = 2

# Config of batch shapes. Only on val.
# We tested YOLOv8-m will get 0.02 higher than not using it.
batch_shapes_cfg = None
# You can turn on `batch_shapes_cfg` by uncommenting the following lines.
# batch_shapes_cfg = dict(
#     type='BatchShapePolicy',
#     batch_size=val_batch_size_per_gpu,
#     img_size=img_scale[0],
#     # The image scale of padding should be divided by pad_size_divisor
#     size_divisor=32,
#     # Additional paddings for pixel scale
#     extra_pad_ratio=0.5)

# -----model related-----
# The scaling factor that controls the depth of the network structure
deepen_factor = 0.33
# The scaling factor that controls the width of the network structure
widen_factor = 0.5
# Strides of multi-scale prior box
strides = [8, 16, 32]
# The output channel of the last stage
last_stage_out_channels = 1024
num_det_layers = 3  # The number of model output scales
norm_cfg = dict(type='BN', momentum=0.03, eps=0.001)  # Normalization config

# -----train val related-----
affine_scale = 0.5  # YOLOv5RandomAffine scaling ratio
# YOLOv5RandomAffine aspect ratio of width and height thres to filter bboxes
max_aspect_ratio = 100
tal_topk = 10  # Number of bbox selected in each level
tal_alpha = 0.5  # A Hyper-parameter related to alignment_metrics
tal_beta = 6.0  # A Hyper-parameter related to alignment_metrics
# TODO: Automatically scale loss_weight based on number of detection layers
loss_cls_weight = 0.5
loss_bbox_weight = 7.5
# Since the dfloss is implemented differently in the official
# and mmdet, we're going to divide loss_weight by 4.
loss_dfl_weight = 1.5 / 4
lr_factor = 0.01  # Learning rate scaling factor
weight_decay = 0.0005
# Save model checkpoint and validation intervals in stage 1
save_epoch_intervals = 1
# validation intervals in stage 2
val_interval_stage2 = 20
# The maximum checkpoints to keep.
max_keep_ckpts = 2
# Single-scale training is recommended to
# be turned on, which can speed up training.
env_cfg = dict(cudnn_benchmark=True)

# ===============================Unmodified in most cases====================
model = dict(
    type='YOLODetector',
    data_preprocessor=dict(
        type='YOLOv5DetDataPreprocessor',
        mean=[0., 0., 0.],
        std=[255., 255., 255.],
        bgr_to_rgb=True),
    backbone=dict(
        type='YOLOv8CSPDarknet',
        arch='P5',
        last_stage_out_channels=last_stage_out_channels,
        deepen_factor=deepen_factor,
        widen_factor=widen_factor,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='SiLU', inplace=True)),
    neck=dict(
        type='YOLOv8PAFPN',
        deepen_factor=deepen_factor,
        widen_factor=widen_factor,
        in_channels=[256, 512, last_stage_out_channels],
        out_channels=[256, 512, last_stage_out_channels],
        num_csp_blocks=3,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='SiLU', inplace=True)),
    bbox_head=dict(
        type='YOLOv8Head',
        head_module=dict(
            type='YOLOv8HeadModule',
            num_classes=num_classes,
            in_channels=[256, 512, last_stage_out_channels],
            widen_factor=widen_factor,
            reg_max=16,
            norm_cfg=norm_cfg,
            act_cfg=dict(type='SiLU', inplace=True),
            featmap_strides=strides),
        prior_generator=dict(
            type='mmdet.MlvlPointGenerator', offset=0.5, strides=strides),
        bbox_coder=dict(type='DistancePointBBoxCoder'),
        # scaled based on number of detection layers
        loss_cls=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='none',
            loss_weight=loss_cls_weight),
        loss_bbox=dict(
            type='IoULoss',
            iou_mode='ciou',
            bbox_format='xyxy',
            reduction='sum',
            loss_weight=loss_bbox_weight,
            return_iou=False),
        loss_dfl=dict(
            type='mmdet.DistributionFocalLoss',
            reduction='mean',
            loss_weight=loss_dfl_weight)),
    train_cfg=dict(
        assigner=dict(
            type='BatchTaskAlignedAssigner',
            num_classes=num_classes,
            use_ciou=True,
            topk=tal_topk,
            alpha=tal_alpha,
            beta=tal_beta,
            eps=1e-9)),
    test_cfg=model_test_cfg)

albu_train_transforms = []

pre_transform = [
    dict(type='LoadImageFromFile', backend_args=_base_.backend_args),
    dict(type='LoadAnnotations', with_bbox=True)
]

last_transform = [
    dict(
        type='mmdet.Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_bboxes_labels', 'gt_ignore_flags']),
        keymap={
            'img': 'image',
            'gt_bboxes': 'bboxes'
        }),
    dict(type='YOLOv5HSVRandomAug'),
    dict(type='mmdet.RandomFlip', prob=0.5),
    dict(
        type='mmdet.PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'flip',
                   'flip_direction'))
]

train_pipeline = [
    *pre_transform,
    dict(
        type='Mosaic',
        img_scale=img_scale,
        pad_val=114.0,
        pre_transform=pre_transform),
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        scaling_ratio_range=(1 - affine_scale, 1 + affine_scale),
        max_aspect_ratio=max_aspect_ratio,
        # img_scale is (width, height)
        border=(-img_scale[0] // 2, -img_scale[1] // 2),
        border_val=(114, 114, 114)),
    *last_transform
]

train_pipeline_stage2 = [
    *pre_transform,
    dict(type='YOLOv5KeepRatioResize', scale=img_scale),
    dict(
        type='LetterResize',
        scale=img_scale,
        allow_scale_up=True,
        pad_val=dict(img=114.0)),
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        scaling_ratio_range=(1 - affine_scale, 1 + affine_scale),
        max_aspect_ratio=max_aspect_ratio,
        border_val=(114, 114, 114)), *last_transform
]

vlm_train_dataset = dict(type='YOLOv5MixedGroundingDataset',
                        data_root='augmented_yolo_train_dataset/',
                        ann_file='annotations/yolo_world_train.json',
                        data_prefix=dict(img='images/'),
                        filter_cfg=dict(filter_empty_gt=False, min_size=32),
                        pipeline=train_pipeline)

train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    persistent_workers=persistent_workers,
    pin_memory=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    collate_fn=dict(type='yolov5_collate'),
    dataset=vlm_train_dataset)

# test_pipeline = [
#     dict(type='LoadImageFromFile', backend_args=_base_.backend_args),
#     dict(type='YOLOv5KeepRatioResize', scale=img_scale),
#     dict(
#         type='LetterResize',
#         scale=img_scale,
#         allow_scale_up=False,
#         pad_val=dict(img=114)),
#     dict(type='LoadAnnotations', with_bbox=True, _scope_='mmdet'),
#     dict(
#         type='mmdet.PackDetInputs',
#         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
#                    'scale_factor', 'pad_param'))
# ]

# val_dataloader = dict(
#     batch_size=val_batch_size_per_gpu,
#     num_workers=val_num_workers,
#     persistent_workers=persistent_workers,
#     pin_memory=True,
#     drop_last=False,
#     sampler=dict(type='DefaultSampler', shuffle=False),
#     dataset=dict(
#         type=dataset_type,
#         data_root=data_root,
#         test_mode=True,
#         data_prefix=dict(img=val_data_prefix),
#         ann_file=val_ann_file,
#         pipeline=test_pipeline,
#         batch_shapes_cfg=batch_shapes_cfg))

# test_dataloader = val_dataloader

param_scheduler = None
optim_wrapper = dict(
    type='OptimWrapper',
    clip_grad=dict(max_norm=10.0),
    optimizer=dict(
        type='SGD',
        lr=base_lr,
        momentum=0.937,
        weight_decay=weight_decay,
        nesterov=True,
        batch_size_per_gpu=train_batch_size_per_gpu),
    constructor='YOLOv5OptimizerConstructor')

default_hooks = dict(
    param_scheduler=dict(
        type='YOLOv5ParamSchedulerHook',
        scheduler_type='linear',
        lr_factor=lr_factor,
        max_epochs=max_epochs),
    checkpoint=dict(
        type='CheckpointHook',
        interval=save_epoch_intervals,
        save_best='auto',
        max_keep_ckpts=max_keep_ckpts))

custom_hooks = [
    dict(
        type='EMAHook',
        ema_type='ExpMomentumEMA',
        momentum=0.0001,
        update_buffers=True,
        strict_load=False,
        priority=49),
    dict(
        type='mmdet.PipelineSwitchHook',
        switch_epoch=max_epochs - close_mosaic_epochs,
        switch_pipeline=train_pipeline_stage2)
]

# val_evaluator = dict(
#     type='mmdet.CocoMetric',
#     proposal_nums=(100, 1, 10),
#     ann_file=data_root + val_ann_file,
#     metric='bbox')
# test_evaluator = val_evaluator

train_cfg = dict(
    type='EpochBasedTrainLoop',
    max_epochs=max_epochs,
    val_interval=save_epoch_intervals,
    dynamic_intervals=[((max_epochs - close_mosaic_epochs),
                        val_interval_stage2)])

# val_cfg = dict(type='ValLoop')
# test_cfg = dict(type='TestLoop')
```

Here is the context of the code that produces the error in albumentation:

```
def _check_args(self, **kwargs: Any) -> None:
        checked_single = ["image", "mask"]
        checked_multi = ["masks"]
        check_bbox_param = ["bboxes"]
        check_keypoints_param = ["keypoints"]
        shapes = []
        print("kwargs keys: ", kwargs.keys())
        print("Available keys:", self._available_keys)
        for data_name, data in kwargs.items():
            if data_name not in self._available_keys and data_name not in ["mask", "masks"]:
                msg = f"Key {data_name} is not in available keys."
                raise ValueError(msg)
```
^^ The print statements above shows a difference in the keys indeed. But I do not understand where I went wrong and how to solve it
```
kwargs keys:  dict_keys(['img_path', 'img_id', 'seg_map_path', 'height', 'width', 'texts', 'is_detection', 'instances', 'sample_idx', 'dataset', 'image', 'img_shape', 'ori_shape', 'gt_ignore_flags', 'bboxes', 'gt_bboxes_labels', 'scale', 'scale_factor', 'homography_matrix', 'pad_param'])
Available keys: {'bboxes', 'gt_bboxes_labels', 'labels', 'gt_ignore_flags'}
```

If I comment out the throwing of the exception, everything proceeds fine until another error happens related to a tensor dimensions mismatch between upsample_features and feat_low. I have no idea if solving this albumentation error might solve the next error but its worth a short. 

Any help will be greatly appreciated

**Comment by wondervictor** [comment]
```bash
pip install albumentations==1.4.4
```

**Comment by XieKaiwen** [comment]
@wondervictor 

> ```shell
> pip install albumentations==1.4.4
> ```
Thanks, this worked. But then after that I still ran into an issue i met beforehand. 

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/jupyter/til-24-base/vlm/YOLO-World/./tools/train.py", line 122, in <module>
[rank0]:     main()
[rank0]:   File "/home/jupyter/til-24-base/vlm/YOLO-World/./tools/train.py", line 118, in main
[rank0]:     runner.train()
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
[rank0]:     model = self.train_loop.run()  # type: ignore
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
[rank0]:     self.run_epoch()
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmengine/runner/loops.py", line 113, in run_epoch
[rank0]:     self.run_iter(idx, data_batch)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmengine/runner/loops.py", line 129, in run_iter
[rank0]:     outputs = self.runner.model.train_step(
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
[rank0]:     losses = self._run_forward(data, mode='loss')
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
[rank0]:     results = self(**data, mode=mode)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
[rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
[rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/jupyter/til-24-base/vlm/mmdetection/mmdet/models/detectors/base.py", line 92, in forward
[rank0]:     return self.loss(inputs, data_samples)
[rank0]:   File "/home/jupyter/til-24-base/vlm/YOLO-World/yolo_world/models/detectors/yolo_world.py", line 30, in loss
[rank0]:     img_feats, txt_feats = self.extract_feat(batch_inputs,
[rank0]:   File "/home/jupyter/til-24-base/vlm/YOLO-World/yolo_world/models/detectors/yolo_world.py", line 100, in extract_feat
[rank0]:     img_feats = self.neck(img_feats, txt_feats)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/jupyter/til-24-base/vlm/vlmvenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/jupyter/til-24-base/vlm/YOLO-World/yolo_world/models/necks/yolo_world_pafpn.py", line 212, in forward
[rank0]:     top_down_layer_inputs = torch.cat([upsample_feat, feat_low], 1)
[rank0]: RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 56 but got size 55 for tensor number 1 in the list.
```
I did not change anything in the yolo_world_pafpn.py file. May get inquire on how should i diagnose the problem or any possible solutions to this.

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
