### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by Niujunbo2002** [AILab-CVC/YOLO-World#353]
python YOLO-World-master/demo/image_demo.py \

Traceback (most recent call last):
  File "/home/underreview/niujunbo/YOLO-World-master/demo/image_demo.py", line 12, in <module>
    from mmdet.apis import init_detector
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py", line 21, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/evaluation/__init__.py", line 3, in <module>
    from .metrics import *  # noqa: F401,F403
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/evaluation/metrics/__init__.py", line 3, in <module>
    from .coco_metric import CocoMetric
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/datasets/__init__.py", line 14, in <module>
    from .utils import get_loading_pipeline
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import ImageToTensor, PackDetInputs, ToTensor, Transpose
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/datasets/transforms/formatting.py", line 9, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/underreview/anaconda3/envs/njb/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

pip list mdurl                     0.1.2
mmcv                      2.0.0
mmcv-lite                 2.2.0
mmdet                     3.0.0
mmengine                  0.10.3
mmyolo                    0.6.0
model-index               0.1.11
mpmath                    1.3.0 
how can i solve this bug?

**Comment by wondervictor** [comment]
see: https://github.com/AILab-CVC/YOLO-World/blob/master/docs/installation.md#install-mmcv

**Comment by Niujunbo2002** [comment]
ok thank u,  i have a try .

**Comment by B10515007** [comment]
https://github.com/AILab-CVC/YOLO-World/issues/573

...
ModuleNotFoundError: No module named 'mmcv._ext'
When you install mmcv by pip, some people will see this error. Because some module of mmcv are not installed.
Solution: Before execute pip to install mmcv, please export this two variables

export MCV_WITH_OPS=1
export FORCE_CUDA=1
then install mmcv

pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html
After install mmcv, we can check if ._ext module is installed successfully

python
import mmcv._ext
