### ISSUE TITLE
OSError: Incorrect path_or_model_id: '../pretrained_models/clip-vit-base-patch32-projection'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

### ISSUE THREAD

**Issue by toutua** [AILab-CVC/YOLO-World#358]
Hello, I encountered the following problem while running the simple_demo.py.
Traceback (most recent call last):
  File "D:\YOLO_World\venv\lib\site-packages\transformers\utils\hub.py", line 399, in cached_file
    resolved_file = hf_hub_download(
  File "D:\YOLO_World\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\YOLO_World\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../pretrained_models/clip-vit-base-patch32-projection'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\YOLO_World\demo\simple_demo.py", line 52, in <module>
    model = init_detector(cfg, checkpoint=checkpoint, device='cuda:0')
  File "D:\YOLO_World\venv\lib\site-packages\mmdet\apis\inference.py", line 66, in init_detector
    model = MODELS.build(config.model)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\YOLO_World\yolo_world\models\detectors\yolo_world.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "D:\YOLO_World\venv\lib\site-packages\mmyolo\models\detectors\yolo_detector.py", line 41, in __init__
    super().__init__(
  File "D:\YOLO_World\venv\lib\site-packages\mmdet\models\detectors\single_stage.py", line 30, in __init__
    self.backbone = MODELS.build(backbone)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\YOLO_World\yolo_world\models\backbones\mm_backbone.py", line 190, in __init__
    self.text_model = MODELS.build(text_model)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\YOLO_World\venv\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\YOLO_World\yolo_world\models\backbones\mm_backbone.py", line 73, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "D:\YOLO_World\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 817, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\YOLO_World\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 649, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\YOLO_World\venv\lib\site-packages\transformers\utils\hub.py", line 463, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '../pretrained_models/clip-vit-base-patch32-projection'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

How can I make changes and where should I place the downloaded file?

**Comment by wondervictor** [comment]
change `../pretrained_models/clip-vit-base-patch32-projection` into `openai/clip-vit-base-patch32`

**Comment by toutua** [comment]
Thank you very much for your reply. This issue has been resolved

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. We sincerely hope that you can give us a star 🌟 and recommend YOLO-World to your friends. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.

**Comment by Allen-Yin-hub** [comment]
@wondervictor @toutua

hello,  i meet the same issue"OSError: Incorrect path_or_model_id: '../pretrained_models/clip-vit-base-patch32-projection'. Please provide either the path to a local folder or the repo_id of a model on the Hub." then i change model_name / text_model_name like what you discuss. however the issue is still exit.

pls give me a hand. thanks.


model_name='openai/clip-vit-base-patch32',
text_model_name = 'openai/clip-vit-base-patch32'

> change `../pretrained_models/clip-vit-base-patch32-projection` into `openai/clip-vit-base-patch32`

**Comment by qiuqiubenren** [comment]
> @wondervictor @toutua
> 
> hello, i meet the same issue"OSError: Incorrect path_or_model_id: '../pretrained_models/clip-vit-base-patch32-projection'. Please provide either the path to a local folder or the repo_id of a model on the Hub." then i change model_name / text_model_name like what you discuss. however the issue is still exit.
> 
> pls give me a hand. thanks.
> 
> model_name='openai/clip-vit-base-patch32', text_model_name = 'openai/clip-vit-base-patch32'
> 
> > change `../pretrained_models/clip-vit-base-patch32-projection` into `openai/clip-vit-base-patch32`

Dear, can u tell me how to change `../pretrained_models/clip-vit-base-patch32-projection` into `openai/clip-vit-base-patch32` or where to change....i completely dont know.Please

**Comment by Allen-Yin-hub** [comment]
> > @wondervictor @toutua
> > hello, i meet the same issue"OSError: Incorrect path_or_model_id: '../pretrained_models/clip-vit-base-patch32-projection'. Please provide either the path to a local folder or the repo_id of a model on the Hub." then i change model_name / text_model_name like what you discuss. however the issue is still exit.
> > pls give me a hand. thanks.
> > model_name='openai/clip-vit-base-patch32', text_model_name = 'openai/clip-vit-base-patch32'
> > > change `../pretrained_models/clip-vit-base-patch32-projection` into `openai/clip-vit-base-patch32`
> 
> Dear, can u tell me how to change `../pretrained_models/clip-vit-base-patch32-projection` into `openai/clip-vit-base-patch32` or where to change....i completely dont know.Please

hello qiuqiu， you can change the parameter in configs files, wheather there is a paremeter named "text_model_name ".

**Comment by lacie-life** [comment]
@Allen-Yin-hub, I had the same problem as you. Have you solved that?

**Comment by Allen-Yin-hub** [comment]
> [@Allen-Yin-hub](https://github.com/Allen-Yin-hub), I had the same problem as you. Have you solved that?

I changed to other model so the issue i don't follow.
