### ISSUE TITLE
onnx模型导出成功，但是运行推理失败。

### ISSUE THREAD

**Issue by Meicsu199345** [AILab-CVC/YOLO-World#362]
感谢非常好的工作。
如题，参考：https://github.com/AILab-CVC/YOLO-World/blob/master/deploy/easydeploy/docs/model_convert.md

生成onnx成功：
PYTHONPATH=./ /mnt/bn/tob-lq/miniconda3/envs/yolo-world/bin/python deploy/export_onnx.py configs/finetune_coco_tob/yolo_world_v2_l_vlpan_bn_sgd_1e-3_40e_8gpus_finetune_coco88.py work_dirs/yolo_world_v2_l_vlpan_bn_sgd_1e-3_40e_8gpus_finetune_coco88/epoch_1.pth --custom-text coco_80_cls_name_list.json --opset 11

但是运行 推理报错：
python main_onnxruntime.py \
        "image_path_to_detect" \
        /mnt/bn/tob-lq/code/yolo/YOLO-World/work_dirs/epoch_1.onnx \
        --out-dir work_dir \
    --img-size 640 640 \
    --show \
    --score-thr 0.3 \
    --iou-thr 0.7

Traceback (most recent call last):
  File "/mnt/bn/tob-lq/code/yolo/YOLO-World/projects/easydeploy/examples/main_onnxruntime.py", line 110, in <module>
    main()
  File "/mnt/bn/tob-lq/code/yolo/YOLO-World/projects/easydeploy/examples/main_onnxruntime.py", line 63, in main
    model_type = ModelType(args.type.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
![image](https://github.com/AILab-CVC/YOLO-World/assets/16251955/43660758-ddce-4e71-8652-1368e33f59f2)

**Comment by kezhang-cs** [comment]
同样的问题, 请问有解决么?

**Comment by andynnnnn** [comment]
同样的问题, 请问有解决么?
