### ISSUE TITLE
the question about image_demo

### ISSUE THREAD

**Issue by Bowie1026** [AILab-CVC/YOLO-World#370]
Hello, thanks for your work! I am a noob and really insterested at your work.
I encountered an error about the connection to huggingface, how could I deal with it?

(yoloworld) root@fdb7e138bfe8:~/data3/zhengby/YOLO-World-master# PYTHONPATH=./ python demo/image_demo.py /root/data3/zhengby/YOLO-World-master/configs/pretrain/yolo_world_v2_xl_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py /root/data3/zhengby/YOLO-World-master/yolo_world_v2_xl_obj365v1_goldg_cc3mlite_pretrain-5daf1395.pth /root/data3/zhengby/GroundingDINO-main/demo_output_13/raw_image.jpg 'painting,cat,table' --topk 100 --threshold 0.005 --output-dir demo_outputs
FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
Traceback (most recent call last):
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f4d94f09850>, 'Connection to huggingface.co timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-base-patch32/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4d94f09850>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-base-patch32/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4d94f09850>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 0a2a8873-5adb-483e-88f3-72e2c3609c59)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/transformers/utils/hub.py", line 399, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/data3/zhengby/YOLO-World-master/demo/image_demo.py", line 179, in <module>
    model = init_detector(cfg, checkpoint=args.checkpoint, device=args.device)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmdet/apis/inference.py", line 66, in init_detector
    model = MODELS.build(config.model)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/data3/zhengby/YOLO-World-master/yolo_world/models/detectors/yolo_world.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmyolo/models/detectors/yolo_detector.py", line 41, in __init__
    super().__init__(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmdet/models/detectors/single_stage.py", line 30, in __init__
    self.backbone = MODELS.build(backbone)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/data3/zhengby/YOLO-World-master/yolo_world/models/backbones/mm_backbone.py", line 190, in __init__
    self.text_model = MODELS.build(text_model)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/data3/zhengby/YOLO-World-master/yolo_world/models/backbones/mm_backbone.py", line 73, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 837, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 934, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/transformers/utils/hub.py", line 442, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-base-patch32 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by wondervictor** [comment]
Hi @Bowie1026, just change "pretrained_models/clip-vit-base-patch32" into "openai/clip-vit-base-patch32".

**Comment by Bowie1026** [comment]
> Hi @Bowie1026, just change "pretrained_models/clip-vit-base-patch32" into "openai/clip-vit-base-patch32".

**thank you. where is "pretrained_models/clip-vit-base-patch32"?** 

and now I meet another error when running the image_demo

`(yoloworld) root@fdb7e138bfe8:~/data3/zhengby/YOLO-World-master# PYTHONPATH=./ python demo/image_demo.py /root/data3/zhengby/YOLO-World-master/configs/pretrain/yolo_world_v2_xl_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py /root/data3/zhengby/YOLO-World-master/yolo_world_v2_xl_obj365v1_goldg_cc3mlite_pretrain-5daf1395.pth /root/data3/zhengby/GroundingDINO-main/demo_output_13/raw_image.jpg 'painting,cat,table' --topk 100 --threshold 0.005 --output-dir demo_outputs
FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
Loads checkpoint by local backend from path: /root/data3/zhengby/YOLO-World-master/yolo_world_v2_xl_obj365v1_goldg_cc3mlite_pretrain-5daf1395.pth
Traceback (most recent call last):
  File "/root/data3/zhengby/YOLO-World-master/demo/image_demo.py", line 179, in <module>
    model = init_detector(cfg, checkpoint=args.checkpoint, device=args.device)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmdet/apis/inference.py", line 102, in init_detector
    metainfo = DATASETS.build(test_dataset_cfg).metainfo
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/data3/zhengby/YOLO-World-master/yolo_world/datasets/mm_dataset.py", line 25, in __init__
    self.dataset = DATASETS.build(dataset)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmyolo/datasets/yolov5_coco.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmdet/datasets/base_det_dataset.py", line 51, in __init__
    super().__init__(*args, **kwargs)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmyolo/datasets/yolov5_coco.py", line 27, in full_init
    self.data_list = self.load_data_list()
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/mmdet/datasets/lvis.py", line 605, in load_data_list
    self.lvis = LVIS(local_path)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/lvis/lvis.py", line 27, in __init__
    self.dataset = self._load_json(annotation_path)
  File "/root/anaconda3/envs/yoloworld/lib/python3.9/site-packages/lvis/lvis.py", line 35, in _load_json
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/lvis/lvis_v1_minival_inserted_image_name.json'
`
could you help me deal with it? I really appreciate it. Thanks for your excellent work!

**Comment by Bowie1026** [comment]
@wondervictor  Thank you for your work. I have figure out that.

**Comment by winnie1228** [comment]
> @wondervictor Thank you for your work. I have figure out that.

I also encountered the same problem, can you tell me how to solve it?
