### ISSUE TITLE
albumentations版本问题

### ISSUE THREAD

**Issue by 937739823** [AILab-CVC/YOLO-World#406]
opencv-python
opencv-python-headless
与
albumentations
对应都是什么版本？ 按basic_requirements.txt装完之后，会报错，按咱们issu里提示albumentations切换成1.4.4版本，微调还是报错，官方能不能提供一个打好包的docker镜像啊，安装花费了很多时间，还没成功。

**Comment by 937739823** [comment]
opencv-python                    4.9.0.80
opencv-python-headless           4.10.0.84
albumentations                   1.4.4

**Comment by 937739823** [comment]
albumentations 由1.4.0版本 升级 1.4.4报错如下：
root@46ad73408c38:/home/hanyong/yolo-world# python tools/train.py configs/finetune_coco/yolo_world_v2_l_vlpan_bn_sgd_1e-3_40e_8gpus_finetune_coco.py   --work-dir log   --amp --resume
Traceback (most recent call last):
  File "tools/train.py", line 9, in <module>
    from mmengine.runner import Runner
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/__init__.py", line 2, in <module>
    from ._flexible_runner import FlexibleRunner
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/_flexible_runner.py", line 20, in <module>
    from mmengine.hooks import Hook
  File "/opt/conda/lib/python3.8/site-packages/mmengine/hooks/__init__.py", line 9, in <module>
    from .naive_visualization_hook import NaiveVisualizationHook
  File "/opt/conda/lib/python3.8/site-packages/mmengine/hooks/naive_visualization_hook.py", line 5, in <module>
    import cv2
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/cv2/typing/__init__.py", line 63, in <module>
    import cv2.gapi.wip.draw
  File "/opt/conda/lib/python3.8/site-packages/cv2/gapi/__init__.py", line 323, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

**Comment by mjq2020** [comment]
实测albumentations==1.3.1可行
