### ISSUE TITLE
ImportError: DLL load failed while importing _ext: 找不到指定的模块。

### ISSUE THREAD

**Issue by RCLaplace** [AILab-CVC/YOLO-World#438]
你好

我按照requirements和readme的步骤配置了环境，但在运行demo的过程中遇到了该问题：

(env1) PS D:\work\2024\7\yolo_world\YOLO-World\demo> python .\image_demo.py
E:\software\VS2019\env\env1\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "D:\work\2024\7\yolo_world\YOLO-World\demo\image_demo.py", line 12, in <module>
    from mmdet.apis import init_detector
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\apis\det_inferencer.py", line 21, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\evaluation\__init__.py", line 3, in <module>
    from .metrics import *  # noqa: F401,F403
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\evaluation\metrics\__init__.py", line 3, in <module>
    from .coco_metric import CocoMetric
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\evaluation\metrics\coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\datasets\__init__.py", line 14, in <module>
    from .utils import get_loading_pipeline
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\datasets\utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\datasets\transforms\__init__.py", line 6, in <module>
    from .formatting import ImageToTensor, PackDetInputs, ToTensor, Transpose
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\datasets\transforms\formatting.py", line 9, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\structures\bbox\__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\structures\bbox\base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "E:\software\VS2019\env\env1\lib\site-packages\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "E:\software\VS2019\env\env1\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "E:\software\VS2019\env\env1\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "E:\software\VS2019\env\env1\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "E:\software\VS2019\shared\Python39_64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。

cuda版本：11.3
python版本： 3.9
pytorch版本： 1.11.0

**Comment by wwwyilei** [comment]
你好，请问你现在解决了吗？
