### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by andynnnnn** [AILab-CVC/YOLO-World#439]
Traceback (most recent call last):
  File "D:\Github\YOLO-World-master\YOLO-World-master\demo\video_demo.py", line 109, in <module>
    main()
  File "D:\Github\YOLO-World-master\YOLO-World-master\demo\video_demo.py", line 93, in main
    visualizer.add_datasample(name='video',
  File "D:\Anaconda\envs\Yolo-world613\lib\site-packages\mmengine\dist\utils.py", line 427, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\Yolo-world613\lib\site-packages\mmdet\visualization\local_visualizer.py", line 371, in add_datasample
    pred_img_data = self._draw_instances(image, pred_instances,
  File "D:\Anaconda\envs\Yolo-world613\lib\site-packages\mmdet\visualization\local_visualizer.py", line 147, in _draw_instances
    label_text = classes[
IndexError: list index out of range
根据之前的 #65 中的建议，我也做了调整cocodataset类别，还是报错~~~请问该如何解决呢谢谢

**Comment by WtElio** [comment]
参考这篇文章 https://blog.csdn.net/qq_36810398/article/details/116994577
