### ISSUE TITLE
Error during Evaluation 

### ISSUE THREAD

**Issue by Mukil07** [AILab-CVC/YOLO-World#47]
While i was running the evaluation script, i ended up with the following error. I tried signing into hugging face using this command `huggingface-cli login`, still ended up with the same error. 

Repository Not Found for url: https://huggingface.co/pretrained_models/clip-vit-base-patch32-projection/resolve/main/tokenizer_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

Also with this error, 

OSError: pretrained_models/clip-vit-base-patch32-projection is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Traceback (most recent call last):
  File "/home/mu480317/.conda/envs/yoloworldnew/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
    response.raise_for_status()
  File "/home/mu480317/.conda/envs/yoloworldnew/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/pretrained_models/clip-vit-base-patch32-projection/resolve/main/tokenizer_config.json

My virtual env has, 

Pytorch 2.0.0
CUDA 11.8
Transformers 4.37.2
huggingface-hub 0.20.3

Please help me solve this error. Thanks !!

**Comment by SuperMaximus1984** [comment]
Same here:
```
OSError: pretrained_models/clip-vit-base-patch32-projection is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass
`use_auth_token=True`.
```
