### ISSUE TITLE
Some undefined keys leading to error while finetuning

### ISSUE THREAD

**Issue by siddankthep** [AILab-CVC/YOLO-World#52]
Hi, I am trying to finetune the model on my object detection dataset. I am using the config for Efficient YOLO-World with the no-mask annotation \_base_. 

In the finetune config file `yolo_world_l_dual_vlpan_2e-4_80e_8gpus_finetune_coco.py`, there are some fields such as `_base_.copypaste_prob` or `_base_.min_area_ratio` that is not present in the _base_ file `yolov8_l_syncbn_fast_8xb16-500e_coco.py`.

I am currently unable to run the finetune scripts due to the errors caused by these keys. Can you provide some methods to tackle this problem? If any more context is needed, please let me know.

**Comment by 997897336** [comment]
同问

**Comment by 997897336** [comment]
@wondervictor 我仍未解决该问题，修改的代码为
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        max_aspect_ratio=100.,
        scaling_ratio_range=(1 - _base_.affine_scale, 1 + _base_.affine_scale),
        # img_scale is (width, height)
        border=(-_base_.img_scale[0] // 2, -_base_.img_scale[1] // 2),
        border_val=(114, 114, 114),
        # min_area_ratio=_base_.min_area_ratio,
        # use_mask_refine=_base_.use_mask2refine)
        use_mask_refine=False)
]



报错
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 109, in __getattr__
    value = super().__getattr__(name)
  File "/usr/local/lib/python3.8/dist-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 138, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 105, in __missing__
    raise KeyError(name)
KeyError: 'copypaste_prob'

**Comment by Sally-lxy** [comment]
> @wondervictor 我仍未解决该问题，修改的代码为 dict( type='YOLOv5RandomAffine', max_rotate_degree=0.0, max_shear_degree=0.0, max_aspect_ratio=100., scaling_ratio_range=(1 - _base_.affine_scale, 1 + _base_.affine_scale), # img_scale is (width, height) border=(-_base_.img_scale[0] // 2, -_base_.img_scale[1] // 2), border_val=(114, 114, 114), # min_area_ratio=_base_.min_area_ratio, # use_mask_refine=_base_.use_mask2refine) use_mask_refine=False) ]
> 
> 报错 Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 109, in **getattr** value = super().**getattr**(name) File "/usr/local/lib/python3.8/dist-packages/addict/addict.py", line 67, in **getattr** return self.**getitem**(item) File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 138, in **getitem** return self.build_lazy(super().**getitem**(key)) File "/usr/local/lib/python3.8/dist-packages/mmengine/config/config.py", line 105, in **missing** raise KeyError(name) KeyError: 'copypaste_prob'

我同样修改以后，也遇到同样的情况，而且我没有在配置文件中找到两个YOLOv5RandomAffine。【 Note that there are two YOLOv5RandomAffine in the config file.】

**Comment by Sally-lxy** [comment]
@997897336 我的问题解决了，在作者提的建议基础上，再注释这一条【dict(type='YOLOv5CopyPaste', prob=_base_.copypaste_prob)】就可以微调了！

**Comment by Sally-lxy** [comment]
![微信截图_20240221165006](https://github.com/AILab-CVC/YOLO-World/assets/74522488/d71f0631-9997-4a0e-aaf8-05df2b49e8bd)

**Comment by wondervictor** [comment]
Hi @siddankthep, @mio410, @Sally-lxy, I've uploaded the new fine-tuning configs without `mask-refine`. You can refer to it now: [yolo_world_l_dual_vlpan_2e-4_80e_8gpus_finetune_coco.py](https://github.com/AILab-CVC/YOLO-World/blob/master/configs/finetune_coco/yolo_world_l_dual_vlpan_2e-4_80e_8gpus_finetune_coco.py)

**Comment by Sally-lxy** [comment]
> @Sally-lxy 您好 想问下您有用微调后的模型来检测一些图片吗，因为我微调后却检测不到任何目标。还有就是您有看过图片的标签信息是否成功读取了吗(将train.py最后几行改成下面这样)？ ![image](https://private-user-images.githubusercontent.com/124493154/306591200-df49f729-9320-4667-8d9e-3d4f9589ae93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTM4MzksIm5iZiI6MTcwOTAxMzUzOSwicGF0aCI6Ii8xMjQ0OTMxNTQvMzA2NTkxMjAwLWRmNDlmNzI5LTkzMjAtNDY2Ny04ZDllLTNkNGY5NTg5YWU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwNTU4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmU3MDlhMzQ2ZDc3YWQ2YTg1ZmI0NjM1ZDE0MzVjYjg3NzIzYjdmY2ZjYjk4NzU5ZDFiOGJkZGI2MWY0ZWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bntzgWZ2u4QZQg1vwCTII2xS4assoqej4pWKttVi4YM)

你好，我现在也是，微调后反而检测不到任何目标了。请问你解决了吗？
