### ISSUE TITLE
Nice work,Bad framwork to use

### ISSUE THREAD

**Issue by Meteplus** [AILab-CVC/YOLO-World#83]
Time is  precious! and it took me a very long time to make the demo to work,the mmlab libray is so ugly while the last version doensn't work,I have to roll it back to 2.0 rc4. my god. why not  to implement the idea on pure pytorch?

**Comment by Y-T-G** [comment]
Yeah. Implement in pure PyTorch and have yet another work that tries to reinvent the wheel and can't even be deployed. MMLab libraries are some of the easiest to use. I am glad they chose that. Otherwise, this project would have died among the dozens of others that can't be productionized.

**Comment by wondervictor** [comment]
Hi @Y-T-G @Meteplus, it's a nice idea to simplify YOLO-World and get rid of the dependent libraries and we are planning to do it.

**Comment by sarhaan7** [comment]
@Meteplus can you share what you changed? I am not able to build this

**Comment by wondervictor** [comment]
Hi @sarhaan7, you can put up your problems here.

**Comment by Meteplus** [comment]
> @Meteplus can you share what you changed? I am not able to build this

Hi,I buit this with PyCharm. when you build the code,it will note you some mmlab libraries are missing, u can just import it in setting->Python Interpreter.It should be noted that as to  mmcv lib you should import the 2.0.0rc4 version rather than the latest version of it . that's all import all missing just follow the IDE's note

**Comment by wondervictor** [comment]
Hi @Meteplus, could you set up the YOLO-World using the command line tools? You can directly install all dependencies through the `setup`.

**Comment by Meteplus** [comment]
> Hi @Meteplus, could you set up the YOLO-World using the command line tools? You can directly install all dependencies through the `setup`.

Did you test this on Ubuntu? I cannot make the setup.py run

**Comment by Meteplus** [comment]
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mmcv

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
ubuntu@ubun:~/YOLO-World$

**Comment by Meteplus** [comment]
using command line, failed to install mmcv2.0.0rc4 .tried to install mmcv2.1.0 then got this:
Traceback (most recent call last):
  File "/home/ubuntu/YOLO-World/demo.py", line 18, in <module>
    from mmyolo.registry import RUNNERS
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mmyolo/__init__.py", line 23, in <module>
    and mmcv_version < digit_version(mmcv_maximum_version)), \
AssertionError: MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

I hate all libries from MMLab .it's ugly and incompatible with their own other version of libs.
